name: Build Flipper CEC Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Clone Flipper Firmware
      run: |
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git flipperzero-firmware
        cd flipperzero-firmware
    
    - name: Setup Flipper Build Environment
      run: |
        cd flipperzero-firmware
        ./fbt --verbose
    
    - name: Copy App to Firmware
      run: |
        mkdir -p flipperzero-firmware/applications/external/cec_test_tool
        cp -r src/* flipperzero-firmware/applications/external/cec_test_tool/
    
    - name: Build Application
      run: |
        cd flipperzero-firmware
        ./fbt fap_cec_test_tool
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flipper-cec-tool-${{ github.sha }}
        path: flipperzero-firmware/build/f7-firmware-D/cec_test_tool.fap
