name: Build Flipper CEC Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Clone Flipper Firmware
      run: |
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git flipperzero-firmware
        cd flipperzero-firmware
    
    - name: Setup Flipper Build Environment
      run: |
        cd flipperzero-firmware
        ./fbt
    
    - name: Copy App to Firmware
      run: |
        mkdir -p flipperzero-firmware/applications/external/cec_test_tool
        cp -r src/* flipperzero-firmware/applications/external/cec_test_tool/
    
    - name: Build CEC App
      run: |
        cd flipperzero-firmware
        ./fbt fap_cec_test_tool
    
    - name: Find and Upload CEC App
      run: |
        cd flipperzero-firmware
        find . -name "*cec*" -name "*.fap" -type f
        mkdir -p ../release
        cp ./dist/f7-D/apps/GPIO/cec_test_tool.fap ../release/ || cp ./build/f7-firmware-D/.extapps/cec_test_tool.fap ../release/
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cec-test-tool-${{ github.sha }}
        path: release/cec_test_tool.fap
