name: Build Flipper CEC Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Clone Flipper Firmware
      run: |
        rm -rf flipperzero-firmware
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git flipperzero-firmware
        cd flipperzero-firmware
    
    - name: Setup Flipper Build Environment
      run: |
        cd flipperzero-firmware
        ./fbt
    
    - name: Copy App to Firmware
      run: |
        mkdir -p flipperzero-firmware/applications/external/cec_test_tool
        cp -r src/* flipperzero-firmware/applications/external/cec_test_tool/
    
    - name: Build All External Apps
      run: |
        cd flipperzero-firmware
        ./fbt fap_dist
    
    - name: Prepare Release Files
      run: |
        mkdir -p release
        if [ -f flipperzero-firmware/build/f7-firmware-C/.extapps/cec_test_tool.fap ]; then
         cp flipperzero-firmware/build/f7-firmware-C/.extapps/cec_test_tool.fap release/
        elif [ -f flipperzero-firmware/build/f7-firmware-D/cec_test_tool.fap ]; then
         cp flipperzero-firmware/build/f7-firmware-D/cec_test_tool.fap release/
        elif [ -f flipperzero-firmware/build/f7-firmware-R/cec_test_tool.fap ]; then
         cp flipperzero-firmware/build/f7-firmware-R/cec_test_tool.fap release/
         else
          echo "App .fap file not found!"
          exit 1
        fi
        cp README.md release/
        cp CHANGELOG.md release/
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cec-test-tool-${{ github.sha }}
        path: release/
