name: Build Flipper CEC Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Clone Flipper Firmware
      run: |
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git flipperzero-firmware
        cd flipperzero-firmware
    
    - name: Setup Flipper Build Environment
      run: |
        cd flipperzero-firmware
        ./fbt
    
    - name: Copy App to Firmware
      run: |
        mkdir -p flipperzero-firmware/applications/external/cec_test_tool
        cp -r src/* flipperzero-firmware/applications/external/cec_test_tool/
    
    - name: Build All Apps (Including CEC)
      run: |
        cd flipperzero-firmware
        ./fbt fap_dist
    
    - name: Extract CEC App
      run: |
        cd flipperzero-firmware
        mkdir -p ../release
        echo "Looking for CEC app..."
        ls -la ./dist/f7-D/apps/GPIO/
        echo "Checking build folder..."
        ls -la ./build/f7-firmware-D/.extapps/ | grep -i cec || echo "No CEC in extapps"
        echo "Copying GPIO apps..."
        cp ./dist/f7-D/apps/GPIO/*.fap ../release/
        echo "Files copied:"
        ls -la ../release/
    
    - name: Upload All GPIO Apps
      uses: actions/upload-artifact@v4
      with:
        name: gpio-apps-${{ github.sha }}
        path: release/
