name: Build Flipper CEC Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Clone Flipper Firmware
      run: |
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git flipperzero-firmware
        cd flipperzero-firmware
    
    - name: Setup Flipper Build Environment
      run: |
        cd flipperzero-firmware
        ./fbt
    
    - name: Copy App to Firmware
      run: |
        mkdir -p flipperzero-firmware/applications/external/cec_test_tool
        cp -r src/* flipperzero-firmware/applications/external/cec_test_tool/
    
    - name: Build CEC App with Error Output
      run: |
        cd flipperzero-firmware
        ./fbt fap_cec_test_tool 2>&1 || echo "Build failed - checking logs"
        echo "=== Checking if CEC app was built ==="
        find . -name "*cec*" -name "*.fap" || echo "No CEC fap found"
        echo "=== All GPIO apps ==="
        find ./dist -name "*.fap" | grep -i gpio || echo "No GPIO apps found"
    
    - name: Upload Debug Info
      uses: actions/upload-artifact@v4
      with:
        name: debug-info-${{ github.sha }}
        path: |
          flipperzero-firmware/applications/external/cec_test_tool/
          flipperzero-firmware/dist/f7-D/apps/GPIO/
